# Generated by Django 3.0.11 on 2024-12-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='쿠폰 코드')),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='쿠폰 할인율')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='상품 이름')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('price', models.PositiveIntegerField(verbose_name='상품 가격(원)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='할인율')),
                ('coupon_applicable', models.BooleanField(default=False, verbose_name='쿠폰 적용 가능 여부')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='상품 카테고리')),
            ],
        ),
    ]
